### PR TITLE
Added tools to check & fix coding style.

### LINKED ISSUE #4: Coding style?
I really like google javascript style. if you agree, I would send PR to make all code as google javascript style.

### PR DESCRIPTION
**Pull request by sunglim**
- Moving extension codes to /extension
- Adding package.json and Gruntfile.js to run jshint and jscsrc. they will check error and style.
- Style fix
- Adding CONTRIBUTING.md to describe how to setup.

Fixes https://github.com/yperess/gerrit-chrome-extension/issues/4

### CODE REVIEW

**Review by yperess — CHANGES_REQUESTED** [review]
I added a pull request to your branch that does the rebase from the updated master. Please review and update (changes are in extension/options.js).

**Comment by yperess** [comment]
Oh, I see, I updated the wrong branch on your repo...

**Comment by sunglim** [comment]
@yperess  I'll update and send PR again.

**Comment by yperess** [comment]
Thanks, sorry about that.

**Comment by sunglim** [comment]
all right. I'll clean up all and send PR including your update.

**Pull request closed without merging**
